name: "linting"

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    name: pr commit
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'release-please[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'release-please[bot]' }}
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  branch-naming-rules:
    name: branch name prefix
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'release-please[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'release-please[bot]' }}
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feat|fix)\/[a-z0-9_-]+$'
          allowed_prefixes: 'feat,fix'
          ignore: main,develop
          min_length: 3
          max_length: 60

  run-tflint:
    name: linting
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'release-please[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'release-please[bot]' }}
    steps:
      - uses: actions/checkout@v5

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Run TFLint
        run: tflint

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

  tests:
    name: global tests
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'release-please[bot]' && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'release-please[bot]' }}
    steps:
      - name: check out called repo
        uses: actions/checkout@v5
        with:
          repository: cloudnationhq/terraform-azure-workflows
          path: called

      - name: setup go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          cache-dependency-path: called/tests/go.sum

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: fetch go modules
        working-directory: called/tests
        run: go mod download

      - name: check out caller repo
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }} # should be able to handle forked PRs, because of the branch prefix
          ref: ${{ github.event.pull_request.head.sha }}
          path: caller
          fetch-depth: 0

      - name: run markdown tests
        working-directory: called/tests
        run: go test -v -run TestReadmeValidation markdown_test.go
        env:
          README_PATH: "${{ github.workspace }}/caller/README.md"
